### ISSUE TITLE
Mutations not returning any data or errors from AppSync server [Reproducible Repo Included]

### ISSUE THREAD

**Issue by Austint30** [awslabs/aws-mobile-appsync-sdk-js#256] opened 2018-09-18 21:08 UTC
EDIT: I have created a repository [here](https://github.com/Austint30/appsync-apollo-mutation-issue) where I was able to reproduce the issue on a small-scale project.

I am trying to use the AWSAppsyncClient in my React web application and I have come across an issue that I have been trying to solve for days to no avail.

I cannot seem to be able to return any data from any of the Mutations I have written. I have tested all of my mutations on the AppSync console and I can confirm all of them do return data and errors. The problem seems to lie within the Client itself (or maybe something is wrong with my setup).

For example, when I call this deleteEntity Mutation I want to display the error message to the screen.
```
<Mutation 
    mutation={DELETE_ENTITY}
    variables={{ _id: record._id, tpID: this.props.orgData.transporter._id }}
    onCompleted={(data) => {console.log('delete data', data); message.success(`Delete successful (${data.deleteEntity})`)}}
    onError={(error) => {console.error(error); message.error('Delete failed: ' + error.message)}}
    refetchQueries={[
        {query, variables: {tpID: this.props.orgData.transporter._id}}
    ]}
    >
{
    (deleteEntity) => (
    <Tooltip title="Delete">
        <Popconfirm placement="left" title="Are you sure you want to delete this?" okText="Delete" onConfirm={() => deleteE
            <Button type="danger" size="small" shape="circle" icon="delete" />
        </Popconfirm>
    </Tooltip>
    )
}
</Mutation>
```

For this, and all similar mutations, no matter what, the data._mutationName_ returned from the mutation is always _null_, and error is always _undefined_ even though this mutations do return data on the AppSync console. This even affects the onError callback function that the react-apollo Mutation component offers.

In my Client setup, I have included an error link as per the [Apollo docs](https://www.apollographql.com/docs/link/links/error.html#error-categories) so I can see the errors in the console. 

When any mutation is run, I do get GraphQL errors in the console like so:
![image](https://user-images.githubusercontent.com/16272815/45715662-61610880-bb5a-11e8-91b8-634d65c703bc.png)

It seems that somehow these errors are failing to make it back to the Mutation component.

Here is how I am setting up the AppSync Client:

```
const stateLink = withClientState({
  cache,
  defaults,
  resolvers: _.merge(transporterResolv, contractsResolv, organizationResolv, customerResolv),
  typeDefs: _.concat(transporterSchem, customerSchem)
});

const appSyncLink = createAppSyncLink({
  ...config.appSync,
  auth: {
    ...config.appSync.auth,
    jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken(),
  },
  disableOffline: true
});

const errorLink = onError(({ graphQLErrors, networkError, operation, forward }) => {
    if (graphQLErrors) {
      for (let err of graphQLErrors) {
          console.log('[Graphql Error]', err);
        switch (err.errorType) {
          case 'UnauthorizedException':
            // error code is set to UNAUTHENTICATED
            // when AuthenticationError thrown in resolver

            // modify the operation context with a new token
            return new Observable(async observer => {
                try{
                    // const creds = await Auth.currentUserCredentials();
                    // creds.refresh(err => {throw Error(err)});
                    const idToken = await Auth.currentSession().idToken;
                    console.log('currentSession', await Auth.currentSession());
                    const oldHeaders = operation.getContext().headers;
                    operation.setContext({
                        headers: {
                            ...oldHeaders,
                            authorization: idToken.jwtToken,
                        },
                    });
                    const subscriber = {
                        next: observer.next.bind(observer),
                        error: observer.error.bind(observer),
                        complete: observer.complete.bind(observer)
                    }
                    forward(operation).subscribe(subscriber);
                }catch(error){
                    console.error('ID Token refresh failed', err)
                    observer.error(error)
                }
            })
        }
      }
    }
    if (networkError) {
      console.log(`[Network error]: ${networkError}`);
    }
  }
);

const link = ApolloLink.from([errorLink, stateLink, appSyncLink])

const AppSyncClientOptions = {
    link
}

const client = new AWSAppsyncClient({}, AppSyncClientOptions);
```

Dependencies from packages.json
```
"dependencies": {
    "antd": "^3.7.2",
    "apollo-boost": "^0.1.15",
    "apollo-cache-inmemory": "^1.2.9",
    "apollo-link": "^1.2.2",
    "apollo-link-error": "^1.1.0",
    "apollo-link-state": "^0.4.1",
    "aws-amplify": "^1.0.2",
    "aws-appsync": "^1.3.4",
    "aws-appsync-react": "^1.1.4",
    "aws-sdk": "^2.302.0",
    "graphql": "^0.13.2",
    "graphql-tag": "^2.9.2",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "qs": "^6.5.2",
    "react": "^16.4.1",
    "react-apollo": "^2.1.11",
    "react-dom": "^16.4.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.4",
    "redux": "^4.0.0",
    "redux-persist": "^5.10.0"
  },
```

**Comment by elorzafe** [comment] 2018-09-19 00:40
@Austint30 did you try just initializing the client like this?

```js
const client = new AWSAppSyncClient({
  url: AppSyncConfig.graphqlEndpoint,
  region: AppSyncConfig.region,
  auth: {
    type: AppSyncConfig.authenticationType,
    apiKey: AppSyncConfig.apiKey,
    // jwtToken: async () => token, // Required when you use Cognito UserPools OR OpenID Connect. token object is obtained previously
  }
});
```

and also are you wrapping your app with apollo provider like this
```
const WithProvider = () => (
  <ApolloProvider client={client}>
    <Rehydrated>
      <App />
    </Rehydrated>
  </ApolloProvider>
)

export default WithProvider
```

Let me know how it goes

**Comment by Austint30** [comment] 2018-09-20 15:38
@elorzafe 
My client initialization is a little more complex than the example your are giving.

In addition to the AWSAppsyncClient I am using apollo-link-state to handle the state of my application locally and apollo-link-error to refresh the user's token when their idToken has expired. 

To explain the spaghetti code below, upon app initialization a query is executed to get the current user's organization (which is a reference to a CouchDB document). An Organization can be either a Customer or a Transporter in which are tied together using contracts. Then, based on the user's organization a list of contracts is queried from the database, and a list of unique customers and transporters is extracted from it and then stored in the cache. From the list of transporters, the first one is selected and stored in the cache. 

TpRouting simply queries the cache and displays the current selected transporter ID as a query parameter in the url using react-router-dom.

```

const DefaultTp = ({children}) => (
    <Query query={TP_QUERY}>
        {({data, loading, error}) => {
        if (loading) return 'Loading...';
        if (error) {
            console.error(error);
            return 'ERROR: ' + error
        }
        // console.log('data', data);
        const { transporter, tpList } = data;
        if (!transporter){
            var newTpID;
            newTpID = tpList[0]._id;
            return <Mutation mutation={TP_MUTATION}>
            {
                (mutate) => {
                mutate({
                    variables: {id: newTpID}
                });
                return null;
                }
            }
            </Mutation>
        }else{
            return children
        }
        }}
    </Query>
)

const NoContracts = (org) => (
    <div>
        <h1>No contracts have been assigned to your organization {org.name}</h1>
    </div>
)

const MutateCache = ({contracts, org}) => (
    <Mutation mutation={INITIALIZE_CACHE}>
        {
            (mutate) => {
                console.log('payload', {contracts, org})
                mutate({
                    variables: {contracts, org}
                })
                return null
            }
        }
    </Mutation>
)

const RenderApp = ({ customer, contracts }) => {
    const app = (
        <AppContext.Provider value={{customer, contracts}}>
            <App />
        </AppContext.Provider>
    )
    if (customer.classType === 'flytsuite.transporter'){
        return (
            <DefaultTp customerID={customer._id}>
                {app}
            </DefaultTp>
        )
    }
    return (
        <DefaultTp customerID={customer._id}>
            <TpRouting>
                {app}
            </TpRouting>
        </DefaultTp>
    )
}

const RenderTpQuery = ({org}) => (
    <Query query={CONTRACTS_TP_QUERY} variables={{id: org._id}} fetchPolicy="network-only">
        {
            ({ data, loading, error }) => {
                if (loading) return <AppLoading />
                if (error) { console.error(error); return error.message}
                const { getContractsByTransporter, contracts } = data;
                if (!getContractsByTransporter.length) return <NoContracts />
                if (contracts.length){
                    return <RenderApp customer={org} contracts={getContractsByTransporter} />
                }
                return <MutateCache contracts={getContractsByTransporter} org={org} />
            }
        }
    </Query>
)

const RenderCusQuery = ({org}) => (
    <Query query={CONTRACTS_CUS_QUERY} variables={{id: org._id}} fetchPolicy="network-only">
        {
            ({ data, loading, error }) => {
                console.log('org', org);
                if (loading) return <AppLoading />
                if (error) { console.error(error); return error.message}
                const { getContractsByCustomer, contracts } = data;
                console.log('getContractsByCustomer', getContractsByCustomer);
                if (!getContractsByCustomer.length) return <NoContracts />
                if (contracts.length){
                    return <RenderApp customer={org} contracts={getContractsByCustomer} />
                }
                return <MutateCache contracts={getContractsByCustomer} org={org} />
            }
        }
    </Query>
)

class AppContainer extends React.Component {
  constructor(props){
    super(props);
    this.state = {
      user: null,
      error: null,
      loading: false
    }
  }
  componentDidMount() {
    this.getUser();
  }
  getUser = async () => {
    this.setState({ loading: true });
    try{
      const user = await Auth.currentAuthenticatedUser();
      this.setState({ user, loading: false });
    }
    catch(error){
      this.setState({ error, loading: false });
    }
  }
  render(){
    const { user, error, loading } = this.state;
    if (loading) {
      return "Loading..."
    }
    if (error) {
      message.error(error.message);
      return <Redirect to="/login" />
    }
    if (user) {
      const id = user.attributes['custom:organization'];
      console.log('id', id);
      return (
        <ApolloProvider client={client}>
            <Rehydrated>
                <Query query={ORG_QUERY} variables={{id}} fetchPolicy="network-only">
                    {
                        ({ data, loading, error }) => {
                            if (loading) return <AppLoading />
                            if (error) {console.error(error); return error.message}
                            const { getOrganization } = data;
                            if (getOrganization.classType === 'flytsuite.transporter'){
                                return <RenderTpQuery org={getOrganization} />
                            }else{
                                return <RenderCusQuery org={getOrganization} />
                            }
                        }
                    }
                </Query>
            </Rehydrated>
        </ApolloProvider>
      )
    }
    return null;
  }
}

export default AppContainer
```

**Comment by MentalBrake** [comment] 2018-09-21 12:29
this happens to me too and this is the client initialization I use:

`export default class App extends Component {
  render() {
    return (
      <Provider client={client}>
        <Rehydrated>
          <Link />
        </Rehydrated>
      </Provider>
    );
  }
}`

**Comment by Austint30** [comment] 2018-09-24 16:58
@elorzafe 
I have created a repository [here](https://github.com/Austint30/appsync-apollo-mutation-issue) where I was able to reproduce the issue on a small-scale project.

**Comment by jrounsav** [comment] 2018-09-24 17:55
I was seeing this as well. Had to set disableOffline to true on the client.

**Comment by Austint30** [comment] 2018-09-25 15:33
@jrounsav Thanks for the workaround. Setting disableOffline does solve the problem. I was actually already setting disableOffline to true, but I was putting it in the createAppSyncLink instead of the AWSAppSyncClient options.

```
const client = new AWSAppsyncClient({
    disableOffline: true
}, { link });
```

**Comment by Austint30** [comment] 2018-09-26 17:31
> The docs should mention that appsync does not currently support offline. I spent almost 48 hours trying to figure what I was doing wrong. Envoyé de mon iPhone
> […](#)
> Le 25 sept. 2018 à 17:41, Austint30 ***@***.***> a écrit : @jrounsav Thanks for the workaround. Setting disableOffline to true does solve the problem. I was actually already setting disableOffline to true, but I was putting it in the createAppSyncLink instead of the AWSAppSyncClient options. This works const client = new AWSAppsyncClient({ disableOffline: true }, { link }); — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Same with me. I've given up after a couple of days and just temporarily treated all of my mutations as a success until a further solution is found.

**Comment by philohelp** [comment] 2018-09-27 11:39
I tested the same code with AWS and GraphCool backend. Optimistic update
does not help. The first update (from local data) is correct, but then the
response from the server seems to void the request and the data turns
undefined.

**Comment by elorzafe** [comment] 2018-09-27 17:09
@Austint30 thanks for sharing your repo. I will clone it now and see what is going on.

I can confirm that this [sample](https://github.com/aws-samples/aws-mobile-appsync-events-starter-react) using aws-appsync@1.3.4 has queries, mutation and subscriptions working.

**Comment by elorzafe** [comment] 2018-09-27 17:11
@Jayphen Thanks for your feedback, we will try to clarify that on our documentation.

**Comment by elorzafe** [comment] 2018-09-27 17:12
@philohelp do you have a code snippet on how your configuring a using the client?

**Comment by elorzafe** [comment] 2018-09-27 18:45
@Austint30 I've tested your app code and could reproduced the problem. I will root cause the problem  now. Thanks for pointing the problem.

**Comment by elorzafe** [comment] 2018-09-27 18:52
@Austint30 @MentalBrake @jrounsav can you try installing aws-appsync@deepdish-next (current version is 1.3.5-link-effect.2)

I've test @Austint30 sample code and has the expected result.

**Comment by elorzafe** [comment] 2018-10-16 18:23
We have fixed this on the latest release (aws-appsync@1.4.0) I will close the issue for now, but feel free to create a new issue if this problem persist.

**Closed by elorzafe** 2018-10-16 18:23 UTC
Labels: bug

**Comment by HuguesRousseau** [comment] 2019-02-07 01:41
Hi, I reproduce the problem using Angular 7 with enableProdMode(). Using `disableOffline: true` makes the problem go away. Is it possible the problem is not fixed with Angular 7?

**Comment by mamach86** [comment] 2019-03-18 12:44
Hi all, same problem here but with queries ("aws-appsync": "^1.7.2") : with `disableOffline: true` works like a charm, but when I try enabling offline and making queries with `fetchPolicy:"cache-first"` I get a null value returned in the data.queryName object, most of the time but not always.

Any update on this ? Thanks a lot

**Comment by mamach86** [comment] 2019-03-23 09:50
> We have fixed this on the latest release (aws-appsync@1.4.0) I will close the issue for now, but feel free to create a new issue if this problem persist.

Hi @elorzafe , I'm having similar issues but with queries (see my post above). By any chance, do you have news about this ?  I opened a new issue here: https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/371

Thanks a lot

**Comment by mzdon** [comment] 2019-04-30 18:24
I was facing this same issue for a while until I found that there was a mismatch between the data I was sending to the server and the graphql input type defined in our AWS AppSync schema!

Our input type had fields that were arrays of strings or arrays of the AWSJSON data type and I was accidentally sending an empty string in one of those fields which caused no matching resolver to be found and in turn the server was ALWAYS returning null instead of all the fields I expected to get back from the mutation.

I would imagine this could affect both queries and mutations if the data types your input doesn't match EXACTLY what the schema defines and is not an issue with the aws appsync sdk itself.

It's too bad the server doesn't just throw a "no matching resolver found" exception.  I suspect quite a few developers are seeing this behavior which is caused by a data to schema mismatch and an error response from the server would make that issue clear as day.

**Comment by akhilvc10** [comment] 2020-01-19 20:17
> I was facing this same issue for a while until I found that there was a mismatch between the data I was sending to the server and the graphql input type defined in our AWS AppSync schema!
> 
> Our input type had fields that were arrays of strings or arrays of the AWSJSON data type and I was accidentally sending an empty string in one of those fields which caused data creation/persistence to fail and in turn the server was ALWAYS returning null instead of all the fields I expected to get back from the mutation.
> 
> I would imagine this could affect both queries and mutations if the data types your input doesn't match EXACTLY what the schema defines and is not an issue with the aws appsync sdk itself.
> 
> It's too bad the server doesn't throw any exceptions. I suspect quite a few developers are seeing this behavior which is caused by a data to schema mismatch and an error response from the server would make that issue clear as day. Maybe those errors are being buried somewhere due to our resolvers...

Facing the same issue. Update mutation not working. It doesn't throw any errors. What would be the possible cause for this ?

Thank alot

**Comment by nayanbhana** [comment] 2020-02-05 22:14
I was just going crazy wondering why my mutation was not invoking! Then finally I saw an error in my console `backend.js:6 TypeError: observer.error is not a function`. This lead me to here, and I added `disableOffline: true` to my config and my mutation was successfully invoking again.

**Comment by anthonyhumphreys** [comment] 2020-02-21 11:18
@elorzafe this still seems to be an issue in 3.0.2 - only way i can get mutations to work is with `disableOffline:true`
