### ISSUE TITLE
Configuring aws-amplify, AppSync for Complex Object Credentials 

### ISSUE THREAD

**Issue by Chandher05** [awslabs/aws-mobile-appsync-sdk-js#336] opened 2019-01-09 06:55 UTC
Right now my configuration aws-amplify 
`Amplify.configure({
  Auth: {
    userPoolId: 'ap-south-xxxx',
    region: 'ap-xxxxx-x',
    identityPoolId: 'xx-xxxx-x',
    userPoolWebClientId: 'xxxxxxxxxxxx',
  },
  API: {
    'aws_appsync_graphqlEndpoint': 'some url',
    'aws_appsync_region': 'ap-xxxxx-5',
    'aws_appsync_authenticationType': 'AWS_IAM',
  }
});`

This above configuration takes care of AppSync calls for me, so I do not manually initialize a appsync client. 
How do I configure Complex Object Credentials, So I can upload to S3 using AppSync with the above configuration.

**Comment by manueliglesias** [comment] 2019-01-14 22:23
Hi @Chandher05 

aws-amplify/amplify-cli#681 seems to be a duplicate of this, I am closing the other issue since this is a sdk question.

This blog post about [Support for complex objects in AWS AppSync](https://aws.amazon.com/blogs/mobile/android-graphql-subscriptions-and-support-for-complex-objects-in-aws-appsync/) might be useful,

The gist is that you pass a `complexObjectsCredentials` key to the `AWSAppSyncClient` constructor to specify which credentials to use when uploading to S3. Typically, you would use Amplify's `Auth.currentCredentials()`:

```ts
const client = new AWSAppSyncClient({
  url: AppSync.graphqlEndpoint,
  region: AppSync.region,
  auth: {
    type: AppSync.authenticationType,
    jwtToken: async () => (await Auth.currentSession()).getAccessToken().getJwtToken(),
  },
  complexObjectsCredentials: () => Auth.currentCredentials(),
});
```

**Comment by kwoxford** [comment] 2019-01-16 09:31
Except then you get this error: 
```
error TS2322: Type 'Promise<ICredentials>' is not assignable to type 'Credentials | CredentialsOptions'.
  Type 'Promise<ICredentials>' is missing the following properties from type 'CredentialsOptions': accessKeyId, secretAccessKey
```

**Comment by attilah** [comment] 2019-01-25 09:23
This PR (https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/305
) was merged just yesterday, this is the solution, I had the very same issue.

**Closed** 2019-04-08 18:28 UTC
Labels: question
