### ISSUE TITLE
Cannot find module '@apollo/client' - introduced by v4.0.4

### ISSUE THREAD

**Issue by leonardomerlin** [awslabs/aws-mobile-appsync-sdk-js#647] opened 2021-06-25 13:53 UTC
>  Note: If your issue/feature-request/question is regarding the AWS AppSync service, please log it in the 
  [official AWS AppSync forum](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0)

**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

```
Error: Cannot find module '@apollo/client'\nRequire stack:\n- /opt/nodejs/node_modules/aws-appsync-subscription-link/lib/subscription-handshake-link.js\n- /opt/nodejs/node_modules/aws-appsync-subscription-link/lib/index.js\n- /opt/nodejs/node_modules/aws-appsync/lib/deltaSync.js\n- /opt/nodejs/node_modules/aws-appsync/lib/cache/offline-cache.js\n- /opt/nodejs/node_modules/aws-appsync/lib/cache/index.js\n- /opt/nodejs/node_modules/aws-appsync/lib/client.js\n- /opt/nodejs/node_modules/aws-appsync/lib/index.js\n- /var/task/appsync/client.js\n- /var/task/middleware/appsync.js\n- /var/task/middleware/index.js\n- /var/task/handlers/appsyncExtractor.js\n- /var/task/handlers.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Try to install the latest `aws-appsync` and run for production, it will break.

**What is the expected behavior?**

Do not break when using in production configuration

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**

- AWS Lambda with NodeJS 14.x

---

I believe it was introduced in the recente MR: `@apollo/client` shouldn't be under `devDependencies` but under `dependencies`.

- PR 646 - https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/646
- https://github.com/awslabs/aws-mobile-appsync-sdk-js/compare/aws-appsync@4.0.3...aws-appsync@4.0.4

**Comment by danrivett** [comment] 2021-06-26 00:53
I can confirm I have also run into this. My deployed lambdas were working fine on Wednesday, but not today.

Here is the stack trace I see in CloudWatch logs:

```
"stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@apollo/client'",
        "Require stack:",
        "- /var/task/node_modules/aws-appsync-subscription-link/lib/subscription-handshake-link.js",
        "- /var/task/node_modules/aws-appsync-subscription-link/lib/index.js",
        "- /var/task/node_modules/aws-appsync/lib/deltaSync.js",
        "- /var/task/node_modules/aws-appsync/lib/cache/offline-cache.js",
        "- /var/task/node_modules/aws-appsync/lib/cache/index.js",
        "- /var/task/node_modules/aws-appsync/lib/client.js",
        "- /var/task/node_modules/aws-appsync/lib/index.js",
        ...internal libary
]
```

After diffing the two lambda versions I deployed I also noticed the change from 4.0.3 to 4.0.4 appears to have caused this error.

One thing that really surprised me to see in a service release update of `aws-appsync` was seeing some of its dependencies be updated to a new major version as that seems risky for a service release?:

```
aws-appsync-auth-link: "^2.0.3" => "^3.0.4"
aws-appsync-subscription-link: "^2.2.1" => "^3.0.6"
```

I assume one or both of those changes is the cause? Which matches the finger being pointed to #646 above.

Although from the stack trace above the finger is pointed at `aws-appsync-subscription-link`, from the diff below of the two deployed lambdas, it appears both `aws-appsync-auth-link` and `aws-appsync-subscription-link` no longer includes `apollo-link`, which I can I assume causes this error?

<img width="1066" alt="lambda-diff" src="https://user-images.githubusercontent.com/30873208/123496667-08154600-d5de-11eb-8fad-1df8ad199cc8.png">

Copying @manueliglesias as the submitter of the suspect PR, and @elorzafe as the reviewer for both your analysis.

**Comment by manueliglesias** [comment] 2021-06-26 01:32
Thank you for the detailed analysis, it helps a lot.

The introduction of `@apollo/client` as a devDependency was to get only the `ApolloLink` type ([here](https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/646/files#diff-36d7b3f05f680500de2a1c4a358a4d58c3d35c04826b43c7761699a949ca12c0R11)), so the plan here will be to migrate to TypeScript 3.8 and make use of [Type-Only imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) so the import is removed from the transpiled code.

In the short term, you can do a `yadd -D @apollo/client`/`npm i -D @apollo/client` to install @apollo/client as a devDependency.

Regarding the dependencies updates:

```
aws-appsync-auth-link: "^2.0.3" => "^3.0.4"
aws-appsync-subscription-link: "^2.2.1" => "^3.0.6"
```

This was supposed to happen in a previous release but was missing.

**Comment by danrivett** [comment] 2021-06-26 02:19
Thanks for the update @manueliglesias but I am unclear how adding a dev dependency on `@apollo/client` will help at runtime?

Maybe I don't understand this enough, is it perhaps because we're using webpack to build our lambdas and according to [this](https://jsramblings.com/do-dependencies-devdependencies-matter-when-using-webpack/) webpack will still include the necessary dev dependency code?

If so, what about others who don't use webpack and just use `tsc` to build their lambdas?

Anyway, I'm currently adding `@apollo/client` as a regular dependency (since it's not really a dev dependency from what I can tell, given the stacktrace at runtime. I will see how that works. But any feedback or suggestions are most welcome as I'm following my nose on this error.

**Comment by danrivett** [comment] 2021-06-26 02:24
My assumption is the upgrade to v `3.x` of `aws-appsync-subscription-link` in particular has caused a dependency on `apollo-link` to no longer be present.

From looking at the dependencies of [`aws-appsync-subscription-link@2.2.1`](https://www.npmjs.com/package/aws-appsync-subscription-link/v/2.2.1) and comparing with [`3.0.6.`](https://www.npmjs.com/package/aws-appsync-subscription-link/v/3.0.6) I see that the dependency on `apollo-link` is gone, (which explains my diff above) but there is a dev dependency on `@apollo/client`.

So I assume that v3 of these files require `@apollo/client` to be installed as a separate dependency. Which makes me wonder why it's not a peer dependency.

Again apologies if these are ignorant thoughts, but I'm struggling to find documentation to help me understand better.

**Comment by danrivett** [comment] 2021-06-26 03:01
> Anyway, I'm currently adding @apollo/client as a regular dependency ... I will see how that works.

Wow, well that just opened the can of worms wider - Now I get the following runtime error - it wants React! I'm running in a Node 14 Lambda, there's definitely no React there.

```
[
        "Runtime.ImportModuleError: Error: Cannot find module 'react'",
        "Require stack:",
        "- /var/task/node_modules/@apollo/client/react/context/context.cjs.js",
        "- /var/task/node_modules/@apollo/client/react/react.cjs.js",
        "- /var/task/node_modules/@apollo/client/main.cjs.js",
        "- /var/task/node_modules/aws-appsync-subscription-link/lib/subscription-handshake-link.js",
        "- /var/task/node_modules/aws-appsync-subscription-link/lib/index.js",
        "- /var/task/node_modules/aws-appsync/lib/deltaSync.js",
        "- /var/task/node_modules/aws-appsync/lib/cache/offline-cache.js",
        "- /var/task/node_modules/aws-appsync/lib/cache/index.js",
        "- /var/task/node_modules/aws-appsync/lib/client.js",
        "- /var/task/node_modules/aws-appsync/lib/index.js",
        ...internal libary
]
```

This is getting concerning, and so I'll leave it to the experts to sort out. For now I'm going to pin our lambdas at `aws-appsync@4.0.3` and avoid all this mess.

**Comment by danrivett** [comment] 2021-06-26 03:43
Just confirming that pinning to `4.0.3` did indeed resolve the issue. Not a long term fix, but will tide me over until the long term fix is made known.

**Comment by nabeelfarid** [comment] 2021-06-26 12:09
> Just confirming that pinning to `4.0.3` did indeed resolve the issue. Not a long term fix, but will tide me over until the long term fix is made known.

Thanks for posting the issue and temp resolution. Spend hours yesterday trying to figure out what went wrong all of a sudden :)

**Comment by tien** [comment] 2021-06-28 23:16
I was lucky enough to have 1 test case blow up from this instead of leaking it to production 🤦‍♂️

**Comment by danrivett** [comment] 2021-07-08 02:14
@manueliglesias any update on this, as you can see from this ticket, there have been many affected by this bug, but there hasn't been any update from the AWS side acknowledging that this is something that needs to be, and will be, fixed on the AWS side, so I just wanted to check in.

We can pin to `4.0.2` in the short-medium term, but not the long term.

As mentioned by all of us, we are using `aws-appsync` in Lambda environments so that's our use case.

If there are better lighterweight alternatives to using that library, I would be open to that if it works with IAM permissions correctly and is straight forward or there are clear instructions.

Currently my setup below works very simply with the IAM permissions automatically set up for the Lambdas by the Serverless framework that deploy my lambda, which is why my following setup has worked really well and has bee very simple to configure, up until `4.0.3`:

```ts
import type { NormalizedCacheObject } from 'apollo-cache-inmemory';
import type { ApolloClientOptions } from 'apollo-client';
import AWSAppSyncClient, { AUTH_TYPE, AWSAppSyncClientOptions } from 'aws-appsync';
import AWS from 'aws-sdk/global';

const { APPSYNC_ENDPOINT, AWS_REGION } = process.env;

const { credentials } = AWS.config;

const appSyncConfig: AWSAppSyncClientOptions = {
  url: APPSYNC_ENDPOINT,
  region: AWS_REGION,
  auth: {
    type: AUTH_TYPE.AWS_IAM,
    credentials,
  },
  disableOffline: true,
};

const apolloClientOptions: Partial<ApolloClientOptions<NormalizedCacheObject>> = {
  defaultOptions: {
    query: {
      fetchPolicy: 'network-only', // important to make sure we get up-to-date results
      errorPolicy: 'all', // Helps log out errors returned from the AppSync GraphQL server
    },
  },
};

export const appSyncClient = new AWSAppSyncClient(appSyncConfig, apolloClientOptions);
```

The one downside is it does cause my Lambda to grow in size a lot even when building with Webpack and my lambda zip currently weighs in at around 18mb.

So if best practice is to avoid using `aws-appsync` in Lambdas we'd be open to that, but as I said it would need to work well as the above has been very good for us until now.

**Comment by Mr0cket** [comment] 2021-07-09 18:35
I am similarly wondering how the AWS team can justify releasing an update knowing that it breaks lambda CD pipelines, and requires a temporary hack to fix.

Why not implement this change AFTER the package has been migrated to TypeScript 3.8?

**Comment by manueliglesias** [comment] 2021-07-09 23:57
Hi,

First of all, I am sorry you had this ugly situation with the packages, after some deep investigation we have validated that things will work as expected.

We just published new versions of the packages, the packages were tested:
- Running inside of a lambda (with both the apollo v2 and apollo v3 compatible versions of the packages)
- Running in the browser (with both the apollo v2 and apollo v3 compatible versions of the packages)

Some basic guidelines:
- If you need offline support, we encourage you to try [AWS Amplify DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js).
- If you want to use the offline capabilities of this sdk you can use the `aws-appsync@latest` as usual.
- If you want to use it inside lambda, you can also use `aws-appsync@latest` with the `disableOffline: true` config option and providing a fetch polyfill for node.
- If you want to use newer versions of Apollo (e.g. v3), you can use just the packages with the custom apollo links (`aws-appsync-auth-link` and `aws-appsync-subscription-link`) as shown in the [README.md](https://github.com/awslabs/aws-mobile-appsync-sdk-js#using-authorization-and-subscription-links-with-apollo-client-no-offline-support)

---

> If there are better lighterweight alternatives to using that library, I would be open to that if it works with IAM permissions correctly and is straight forward or there are clear instructions.

@danrivett We provide instructions on [how to call an AppSync GraphQL API from a Node.js app or a Lambda function](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js), there you will also find information on [how to sign the request using IAM credentials](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js#signing-a-request-from-lambda)

Thank you for the patience

**Closed** 2021-07-21 17:43 UTC
Labels: pending-close-response-required
