### ISSUE TITLE
Best practice for real-time data syncing

### ISSUE THREAD

**Issue by jmparsons** [awslabs/aws-mobile-appsync-sdk-js#139] opened 2018-05-27 18:18 UTC
In the case of many inserts happening at the same time I've noticed the graphql subscriptions not catching many of them. A simple example would be to take the provided sample schema and project, then spam the add comment button on an event - I've canned some Math random message to auto generate a comment on click. I've tried to increased the read and write capacity units, but the results are the same. Spamming up to three comment inserts will work just fine, but anything more and they don't get added - two browsers side by side showing the same event page.

**Comment by ryanwmarsh** [comment] 2018-05-28 02:03
@jmparsons This is very interesting. Do you have a demo you could share?

**Comment by jmparsons** [comment] 2018-05-28 02:11
I really did just create new sample schema and downloaded the starter app then ran it with the credentials and changed the create comment to use a canned message instead of the text field.

**Comment by ryanwmarsh** [comment] 2018-05-28 02:52
@jmparsons I just created the sample schema and downloaded the sample app. 

In `NewComment.js` after: 
```
    await createComment({
      ...comment,
      eventId,
      createdAt: moment.utc().format()
    })
```
I added this.
```
Promise.all(
  [...Array(10).keys()].map(e =>
    createComment({
      content: `${e}`,
      eventId,
      createdAt: moment.utc().format()
    })
  )
)
```

I get my comment, plus 10 additional numbered comments. Although they do arrive out of order. I'm using Firefox and Chrome and watching it happen to both. It's not instantaneous but it resolves in under 3 seconds.

**Comment by jmparsons** [comment] 2018-05-28 02:57
Try to stagger the calls. I changed:

```js
const { comment } = this.state;
```

to:

```js
const comment = { content: `hi-${Math.random().toString()}` };
```

Then placed the add comment button above the list so I could spam click it:

```js
{[].concat(items).sort((a, b) => a.createdAt.localeCompare(b.createdAt)).map(this.renderComment)}
<NewComment eventId={eventId} />
```

```js
<NewComment eventId={eventId} />
{[].concat(items).sort((a, b) => a.createdAt.localeCompare(b.createdAt)).map(this.renderComment)}
```

**Comment by ryanwmarsh** [comment] 2018-05-28 03:05
@jmparsons I did notice a weird bug where my comments are being duplicated once GraphQL tries to sync with the API. Wait for it.

![](https://thumbs.gfycat.com/NastyUnluckyIbizanhound-size_restricted.gif)

**Comment by ryanwmarsh** [comment] 2018-05-28 03:15
@jmparsons Now I'm getting some really weird behavior. Try this and submit one comment after the other. Then refresh the page. The second set of comment+numbers are disappearing on me.

```
    await createComment({
      ...comment,
      eventId,
      createdAt: moment.utc().format()
    })

    Promise.all(
      [...Array(10).keys()].map(n =>
        createComment({
          content: `${n} ${Math.random().toString()}`,
          eventId,
          createdAt: moment.utc().format()
        })
      )
    )
```

**Comment by jmparsons** [comment] 2018-05-28 03:28
@ryanwmarsh Yeah same thing for me.

**Comment by ryanwmarsh** [comment] 2018-05-28 03:38
@jmparsons The deeper I dig and more permutations I try (run mutations from AppSync console, etc...) the more weirdness I'm finding. Either I'm using AppSync wrong or there are problems with the AppSync SDK. I'd like to find out which because right now I can't put something like this into production.

**Comment by jmparsons** [comment] 2018-05-28 06:16
@ryanwmarsh I'm in the same boat. If the syncing isn't spot on I'm going to have to resort to polling. I can't sort and filter the results, but the actual data has missing inserts.

**Comment by jmparsons** [comment] 2018-05-29 20:29
@undefobj on it.

**Comment by dennari** [comment] 2018-08-05 09:42
Any news on this? I'm considering AppSync mainly for real-time data syncing and this looks worrisome.

**Comment by undefobj** [comment] 2018-08-05 20:17
@dennari we are still tracking this and have a design, but it's a very particular edge case for very high velocity writes on sync that we need to implement carefully to ensure data integrity. Are you running into this in production? It shouldn't be common for most use cases, as members such as @jmparsons had to write code with many elements in a loop to reproduce.

**Comment by arelaxend** [comment] 2018-08-29 22:04
Hi, I have found the same issue, I have a subscription and many mutate to update state of the app (to do a loading feature), and some mutations do not trigger events!

**Comment by elorzafe** [comment] 2018-12-20 01:21
@jmparsons @dennari @arelaxend @ryanwmarsh have you tried latest aws-appsync(1.7.0), high velocity writes shouldn't be an issue right now. Let me know how it goes. Otherwise I will close this issue in a week from now.

Thanks!

**Comment by ryanwmarsh** [comment] 2018-12-20 23:37
Thanks, you can close this.

**Closed** 2018-12-20 23:54 UTC
Labels: pending-close-response-required
