### ISSUE TITLE
Problem with mutations with appsync client

### ISSUE THREAD

**Issue by micahjonas** [awslabs/aws-mobile-appsync-sdk-js#170] opened 2018-07-02 13:54 UTC
Hi,  I'm currently setting up a new project with AppSync and React and I'm running into problems with mutations. Fetching data works fine but when I try to do any mutation the response somehow crashes. The backend receives the mutation and changes the data, but in the appsync client something goes worng and I get the following errors:

> offline-link.js:97 Uncaught TypeError: Cannot read property 'queryManager' of undefined
>     at Object.next (offline-link.js:97)
>     at notifySubscription (Observable.js:126)
>     at onNotify (Observable.js:161)
>     at SubscriptionObserver.next (Observable.js:215)
>     at notifySubscription (Observable.js:126)
>     at onNotify (Observable.js:161)
>     at SubscriptionObserver.next (Observable.js:215)
>     at notifySubscription (Observable.js:126)
>     at onNotify (Observable.js:161)
>     at SubscriptionObserver.next (Observable.js:215)
>     at httpLink.js:91

The mutation is executed in the backend and the proper information is submitted back to the browser. But the AppSync Client for some reason can't handle the response. If I setup an ApolloClient with 'apollo-boost' and connect it to the same endpoint everything works as expected. Is there something wrong with my query or does the AppSync client require a diffrent setup?

Some code:

```
const client = new AWSAppSyncClient({
  url: config.graphqlEndpoint,
  region: config.region,
  auth: {
    type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
    jwtToken: async () => (await Auth.currentSession()).idToken.jwtToken
  }
});
```

Mutation:

```
client
  .mutate({
    mutation: gql`
      mutation addManagementArea($name: String!) {
        addManagementArea(name: $name) {
          __typename
          id
          name
        }
      }
    `,
    variables: { name: "test 123" }
  })
  .then(data => console.log("success", data))
  .catch(error => console.error("error", error));
```

If I'm running the same query with just the ApolloClient and the same setup I get a response back:

```
const client = new ApolloClient({
  uri: config.graphqlEndpoint,
  request: async operation => {
    operation.setContext({
      headers: {
        authorization: (await Auth.currentSession()).idToken.jwtToken
      }
    });
  }
});
```
Package.json:

```
{
  "name": "resido-web-client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "amazon-cognito-identity-js": "2.0.6",
    "apollo-boost": "^0.1.10",
    "aws-amplify": "^0.4.1",
    "aws-appsync": "^1.1.2",
    "aws-appsync-react": "^1.0.17",
    "graphql-tag": "^2.9.2",
    "moment": "^2.22.1",
    "react": "16.4.0",
    "react-apollo": "2.1.4",
    "react-dom": "16.4.0",
    "react-redux": "^5.0.7",
    "react-router-dom": "4.2.2",
    "react-scripts": "1.1.4",
    "react-waypoint": "^8.0.1",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0",
    "uuid": "^3.2.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by mwarger** [comment] 2018-07-03 02:31
If it's any help at all - I have this same issue as above.  Additionally, immediately before the above error I receive this through my error link logger:

```
message
:
"Cannot read property 'data' of undefined"
stack
:
"TypeError: Cannot read property 'data' of undefined↵    at Mutation._this.onCompletedMutation (http://localhost:3000/static/js/bundle.js:116739:37)↵    at http://localhost:3000/static/js/bundle.js:116697:27"
```

I know that's not much more to go on, but figured I'd leave it all the same.

**Comment by mwarger** [comment] 2018-07-03 21:50
@micahjonas This appears to be fixed in the "deepdish" version.  I just tried it and didn't face any issues.

`yarn add aws-appsync@deepdish aws-appsync-react@deepdish` - this is probably unstable, but good enough for my needs at the moment.

**Comment by nilsga** [comment] 2018-07-05 13:23
I have the same issue. Working my way backwards, I found that the latest version where this works is in version 1.0.22.

**Comment by nilsga** [comment] 2018-07-05 17:37
Diff between last working and first non working: aws-appsync@1.0.22...aws-appsync@1.0.23

So it's probable that either #143 or #146 is the culprit.

**Comment by manueliglesias** [comment] 2018-07-05 22:13
Hi @micahjonas , @mwarger , @nilsga 

I've looked at the issue, and I think I know what is happening. Using offline capabilities in the SDK only make sense if you provide an `optimisticResponse` to your `client.mutate` call. Can you try providing an `optimisticReponse`?

Also, there will be a PR soon with a fix to better handle these scenarios.

Let me know how it goes.

**Comment by nilsga** [comment] 2018-07-05 22:20
That might be an issue, too. But this used to work without supplying an optimisticResponse, so I don’t think that’s the cause of this particular issue.

**Comment by mwarger** [comment] 2018-07-05 22:37
I still received the error after supplying an optimistic response. I
thought that could be it too and tried it without luck.

**Closed** 2018-07-10 21:17 UTC

**Comment by akiran** [comment] 2018-09-12 17:20
I can also confirm this issue. Latest version of app sync is returning mutation response as null.

Reverting aws-appsync and aws-appsync-react to 1.0.22 and 1.0.13  as @alez007 mentioned is working.

@micahjonas Can you reopen this issue

**Comment by alez007** [comment] 2018-09-12 17:31
One more thing,I managed to use the latest version if I set disableOffline
to true.

**Comment by akiran** [comment] 2018-09-12 17:45
@alez007 With aws-appsync 1.3.4 and aws-appsync-react 1.14, setting disableOffline
to true didn't work for me.

Which versions are you using now ?

**Comment by micahjonas** [comment] 2018-09-13 06:50
Hi guys I solved my issues some time ago with just using apollo and aws-amplify directly. I don't seem to have the priviliges to reopen this issue. Maybe somebody has to reopen e new one and maybe reference this issue.

**Comment by alez007** [comment] 2018-09-13 07:26
> @alez007 With aws-appsync 1.3.4 and aws-appsync-react 1.14, setting disableOffline
> to true didn't work for me.
> 
> Which versions are you using now ?

My current versions are: 1.3.4 and 1.1.4.

**Comment by alez007** [comment] 2018-09-13 07:29
> Hi guys I solved my issues some time ago with just using apollo and aws-amplify directly. I don't seem to have the priviliges to reopen this issue. Maybe somebody has to reopen e new one and maybe reference this issue.

Yes, the thought crossed my mind, I'm not really content with the progress of this library tbh. Updates are slow and brief, pull requests are just sitting there, issue number just goes up, etc.

**Comment by elorzafe** [comment] 2018-09-13 17:59
We are preparing a new version that has many internal changes, it should address the issues you mentioned before, however the api remains the same. 

You can try our latest beta version on @deepdish-next tag (1.3.5-link-effect.2)

**Comment by bergie** [comment] 2018-09-22 16:42
@elorzafe can verify that `1.3.4` returns a `null`, and `@deepdish-next` fixes this. What's the planned release date for this?
